download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/nokia-srlinux-0.4.0.tar.gz
format_version: 1.0.0
name: srlinux
namespace: nokia
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.4.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/nokia/srlinux/versions/0.4.0/
