- name: Push ACL configuration
  gather_facts: false
  hosts: all
  tasks:
    - name: Apply generated ACL
      nokia.srlinux.config:
        # NOTE: this should be safe-ish
        update:
          - path: /acl/
            value: "{{lookup('file', './srl.srl_acl') | from_json}}"
      # register: set_response
